name: smart_fitting_room
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_dotenv: ^6.0.0
  cupertino_icons: ^1.0.8
  
  # Supabase
  supabase_flutter: ^2.10.3

  # Cámara
  camera: ^0.10.5+5

  # Stacked
  stacked: ^3.4.1

  # Permisos
  permission_handler: ^11.3.1

  google_mlkit_pose_detection: ^0.12.1
  google_mlkit_commons: ^0.8.1

  url_launcher: ^6.3.0
  flutter_pdfview: ^1.4.3
  path_provider: ^2.1.5
  http: ^1.2.2
  google_fonts: ^6.2.1
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # 👇 Paquete para generar los íconos de la app
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/docs/
    # (no hace falta registrar aquí el icono, el paquete lo toma directo del path)

# 👇 Configuración de flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
    background_color: "#020617"
    theme_color: "#020617"
  macos:
    generate: true
    image_path: "assets/icons/app_icon.png"
  windows:
    generate: true
    image_path: "assets/icons/app_icon.png"
  linux:
    generate: true
    image_path: "assets/icons/app_icon.png"
